# Generated by Django 2.2.28 on 2023-05-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('cim', models.CharField(max_length=200)),
                ('belso_meret', models.CharField(max_length=200)),
                ('kulso_meret', models.CharField(max_length=200)),
                ('ar', models.IntegerField()),
                ('leiras', models.CharField(max_length=500)),
                ('eladva', models.BooleanField()),
                ('feltoltott_kep', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Kosar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepek', models.ManyToManyField(to='haplmelinda_oldal.Kep')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teljes_nev', models.CharField(blank=True, default='', max_length=200)),
                ('telefon', models.CharField(blank=True, default='', max_length=15)),
                ('szallitasi_hely', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rendeles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haplmelinda_oldal.Profile')),
                ('kosar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haplmelinda_oldal.Kosar')),
            ],
        ),
        migrations.AddField(
            model_name='kosar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haplmelinda_oldal.Profile'),
        ),
        migrations.AddField(
            model_name='kep',
            name='technika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haplmelinda_oldal.Technika'),
        ),
        migrations.AddField(
            model_name='kep',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haplmelinda_oldal.Tema'),
        ),
    ]
