# Generated by Django 3.2.5 on 2022-12-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('cim', models.CharField(max_length=200)),
                ('leiras', models.CharField(max_length=500)),
                ('ar', models.IntegerField()),
                ('belso_meret', models.CharField(max_length=200)),
                ('kulso_meret', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=200)),
                ('technika', models.CharField(max_length=200)),
                ('eladva', models.BooleanField()),
                ('kep', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
