# Generated by Django 2.2.28 on 2023-05-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haplmelinda_oldal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosar',
            old_name='user',
            new_name='profile',
        ),
    ]
