# Generated by Django 2.2.28 on 2023-05-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haplmelinda_oldal', '0002_auto_20230505_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendeles',
            name='total_price',
        ),
    ]
