# Generated by Django 2.2.28 on 2023-05-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haplmelinda_oldal', '0003_remove_rendeles_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendeles',
            old_name='customer',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='rendeles',
            name='created_at',
        ),
    ]
