# Generated by Django 2.2.28 on 2023-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haplmelinda_oldal', '0004_auto_20230505_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendeles',
            name='profile',
        ),
        migrations.AddField(
            model_name='rendeles',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
