// Képek adatai - CSV-ből konvertálva
// Ha a képek máshogy vannak elnevezve, itt módosítsd az id értékeket

const galleryData = [
  {
    id: 107, // vagy a tényleges fájlnév (pl. "erdoben_nappall_es_ejjel")
    title: "Erdőben nappal és éjjel",
    size: "39.0x29.0",
    externalSize: "42.9x22.8",
    price: 30000,
    category: "természet",
    technique: "fa",
    description: "kész",
    sold: false,
  },
  {
    id: 74,
    title: "Indás nő",
    size: "15.0x30.8",
    externalSize: "21.4x37.5",
    price: 30000,
    category: "női alak",
    technique: "fa",
    description: "...",
    sold: false,
  },
  {
    id: 76,
    title: "Hableány",
    size: "15.0x31.0",
    externalSize: "21.4x37.5",
    price: 30000,
    category: "női alak",
    technique: "fa",
    description: "kész",
    sold: false,
  },
  {
    id: 71,
    title: "Erdőben a nő",
    size: "15.2x31.2",
    externalSize: "23.5x39.5",
    price: 30000,
    category: "női arc",
    technique: "fa",
    description: "...",
    sold: false,
  },
  // {
  //   id: 99,
  //   title: "Levelek között",
  //   size: "24.1x24.1",
  //   externalSize: "27.8x27.8",
  //   price: 30000,
  //   category: "női alak",
  //   technique: "fa",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 91,
    title: "Cseresznyefa virág",
    size: "8.1x25.0",
    externalSize: "18.4x35.3",
    price: 30000,
    category: "virág",
    technique: "...",
    description: "kész",
    sold: false,
  },
  {
    id: 90,
    title: "Kék pipacs",
    size: "8.1x25.0",
    externalSize: "18.4x35.3",
    price: 30000,
    category: "virág",
    technique: "...",
    description: "kész",
    sold: false,
  },
  {
    id: 62,
    title: "Páva",
    size: "18.4x23.5",
    externalSize: "26.9x31.9",
    price: 30000,
    category: "állat",
    technique: "porcelán",
    description: "kész",
    sold: false,
  },
  {
    id: 104,
    title: "Szellőrózsa",
    size: "18.1x24.3",
    externalSize: "25.4x31.2",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  {
    id: 96,
    title: "Indák királynője",
    size: "11.1x20.1",
    externalSize: "19.8x28.8",
    price: 30000,
    category: "női alak",
    technique: "...",
    description: "kész",
    sold: false,
  },
  {
    id: 100,
    title: "Fehér virágok (olaj vászon)",
    size: "18.2x24.3",
    externalSize: "25.3x31.5",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  {
    id: 102,
    title: "Fehér pipacs",
    size: "18.2x24.4",
    externalSize: "25.3x31.5",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  {
    id: 31,
    title: "Pipacs",
    size: "16.1x16.1",
    externalSize: "24.6x24.6",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 101,
    title: "Tulipánfa",
    size: "18.1x24.6",
    externalSize: "25.3x31.4",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  {
    id: 105,
    title: "Bordó tulipánok",
    size: "18.1x24.6",
    externalSize: "25.3x31.4",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  // {
  //   id: 1005,
  //   title: "Dombos táj",
  //   size: "9.4x6.5",
  //   externalSize: "18.1x13.1",
  //   price: 30000,
  //   category: "...",
  //   technique: "...",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 1036,
  //   title: "Fa a domboldalon",
  //   size: "6.1x9.6",
  //   externalSize: "14.3x17.8",
  //   price: 30000,
  //   category: "...",
  //   technique: "...",
  //   description: "...",
  //   sold: false,
  // },
  {
    id: 95,
    title: "Tűz királynő",
    size: "20.9x14.8",
    externalSize: "29.5x23.5",
    price: 30000,
    category: "női alak",
    technique: "fa",
    description: "kész",
    sold: false,
  },
  {
    id: 24,
    title: "Bimbós hölgy",
    size: "15.1x12.1",
    externalSize: "27.4x21.4",
    price: 30000,
    category: "női arc",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  // {
  //   id: 7,
  //   title: "Balerina",
  //   size: "20.1x15.3",
  //   externalSize: "29.5x24.5",
  //   price: 30000,
  //   category: "női alak",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 2,
    title: "Dombos táj",
    size: "20.1x15.0",
    externalSize: "26.9x21.737",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  // {
  //   id: 37,
  //   title: "Dombos táj",
  //   size: "4.2x10.8",
  //   externalSize: "13.1x17.9",
  //   price: 30000,
  //   category: "természet",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 40,
    title: "Magányos fa",
    size: "6.3x9.2",
    externalSize: "12.1x15.1",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 79,
    title: "Egymáshoz érve (háttal)",
    size: "24.0x11.6",
    externalSize: "34.3x17.9",
    price: 30000,
    category: "szerelem",
    technique: "...",
    description: "kész",
    sold: false,
  },
  {
    id: 11,
    title: "Fénybe néző",
    size: "9.8x18.9",
    externalSize: "18.9x27.3",
    price: 30000,
    category: "női arc",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 86,
    title: "Mandala 2",
    size: "23.9x23.9",
    externalSize: "27.6x27.6",
    price: 30000,
    category: "mandala",
    technique: "fa",
    description: "...",
    sold: false,
  },
  {
    id: 26,
    title: "Szent család",
    size: "24.3x19.8",
    externalSize: "33.1x28.1",
    price: 30000,
    category: "...",
    technique: "tűzzománc",
    description: "...",
    sold: false,
  },
  // {
  //   id: 17,
  //   title: "Szerelem",
  //   size: "23.0x17.1",
  //   externalSize: "32.4x26.5",
  //   price: 30000,
  //   category: "szerelem",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 82,
    title: "Ég és föld között",
    size: "19.8x14.8",
    externalSize: "34.0x28.0",
    price: 30000,
    category: "női alak",
    technique: "fa",
    description: "...",
    sold: false,
  },
  {
    id: 70,
    title: "Karcnő",
    size: "29.2x19.3",
    externalSize: "34.7x24.7",
    price: 30000,
    category: "női alak",
    technique: "vászon",
    description: "...",
    sold: false,
  },
  {
    id: 1002,
    title: "Három lány",
    size: "9.9x27.1",
    externalSize: "20.2x39.3",
    price: 30000,
    category: "...",
    technique: "...",
    description: "...",
    sold: false,
  },
  {
    id: 1,
    title: "Erdőben",
    size: "20.1x21.8",
    externalSize: "26.8x21.8",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "...",
    sold: false,
  },
  {
    id: 103,
    title: "Sárga liliom",
    size: "14.3x18.0",
    externalSize: "31.0x25.1",
    price: 30000,
    category: "virág",
    technique: "vászon",
    description: "kész",
    sold: false,
  },
  // {
  //   id: 110,
  //   title: "Őszi lány fakerettel",
  //   size: "7.0x9.3",
  //   externalSize: "18.4x18.4",
  //   price: 30000,
  //   category: "...",
  //   technique: "...",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 83,
    title: "Fa a domb előtt",
    size: "15.3x9.9",
    externalSize: "22.4x17.0",
    price: 30000,
    category: "természet",
    technique: "fa",
    description: "kész",
    sold: false,
  },
  {
    id: 61,
    title: "Liliom",
    size: "24.0",
    externalSize: "24.0",
    price: 30000,
    category: "virág",
    technique: "fa",
    description: "...",
    sold: false,
  },
  // {
  //   id: 23,
  //   title: "Őszi hölgy",
  //   size: "14.2x11.2",
  //   externalSize: "20.2x17.3",
  //   price: 30000,
  //   category: "női arc",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 5,
  //   title: "Imádkozó kereszt",
  //   size: "9.9x5.1",
  //   externalSize: "21.1x21.1",
  //   price: 30000,
  //   category: "vallási témájú",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 12,
    title: "Nyári lány",
    size: "9.8x7.9",
    externalSize: "21.4x19.4",
    price: 30000,
    category: "női arc",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 10,
    title: "Őszi lány",
    size: "9.8x7.9",
    externalSize: "21.4x19.4",
    price: 30000,
    category: "női arc",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 15,
    title: "Esőben",
    size: "9.8x7.9",
    externalSize: "21.4x19.4",
    price: 30000,
    category: "női alak",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 63,
    title: "Keltai kereszt",
    size: "18.6x8.1",
    externalSize: "22.8x12.8",
    price: 30000,
    category: "vallási téma",
    technique: "porcelán",
    description: "kész",
    sold: false,
  },
  {
    id: 64,
    title: "Tápiószentmártoni szkíta aranyszarvas",
    size: "9.1x19.1",
    externalSize: "12.9x22.8",
    price: 30000,
    category: "állat",
    technique: "porcelán",
    description: "kész",
    sold: false,
  },
  {
    id: 65,
    title: "Zöldhalompusztai szkíta aranyszarvas",
    size: "9.1x19.1",
    externalSize: "12.9x22.8",
    price: 30000,
    category: "állat",
    technique: "porcelán",
    description: "kész",
    sold: false,
  },
  {
    id: 1033,
    title: "Orchidea",
    size: "14.3x9.5",
    externalSize: "17.2x12.3",
    price: 30000,
    category: "...",
    technique: "...",
    description: "...",
    sold: false,
  },
  {
    id: 30,
    title: "Folyó szélén",
    size: "9.7x19.6",
    externalSize: "12.3x22.2",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 13,
    title: "Hosszú hajú lány",
    size: "9.9x7.9",
    externalSize: "21.4x19.4",
    price: 30000,
    category: "női alak",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 42,
    title: "Szőke hajú nő",
    size: "4.0x9.0",
    externalSize: "9.6x14.7",
    price: 30000,
    category: "női arc",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  // {
  //   id: 9,
  //   title: "Szerelem",
  //   size: "9.5x6.6",
  //   externalSize: "21.0x18.2",
  //   price: 30000,
  //   category: "szerelem",
  //   technique: "tűzzománc",
  //   description: "kész",
  //   sold: false,
  // },
  {
    id: 8,
    title: "Egymásba olvadva",
    size: "9.5x6.6",
    externalSize: "21.0x18.2",
    price: 30000,
    category: "szerelem",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 21,
    title: "Táncoló lány",
    size: "15.0x12.0",
    externalSize: "27.3x21.4",
    price: 30000,
    category: "női alak",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 1003,
    title: "Üveg",
    size: "14.7",
    externalSize: "14.7",
    price: 30000,
    category: "...",
    technique: "...",
    description: "...",
    sold: false,
  },
  {
    id: 85,
    title: "Mandala 1",
    size: "10.2x10.2",
    externalSize: "19.3x19.3",
    price: 30000,
    category: "vallási téma",
    technique: "fa",
    description: "kész",
    sold: false,
  },
  {
    id: 84,
    title: "Halak kövekkel",
    size: "10.2x10.2",
    externalSize: "19.3x19.3",
    price: 30000,
    category: "...",
    technique: "...",
    description: "kész",
    sold: false,
  },
  {
    id: 57,
    title: "Liliom hölgy",
    size: "14.2x8.6",
    externalSize: "17.2x11.7",
    price: 30000,
    category: "női alak",
    technique: "porcelán",
    description: "kész",
    sold: false,
  },
  {
    id: 38,
    title: "Indák között",
    size: "9.2x9.2",
    externalSize: "15.0x15.0",
    price: 30000,
    category: "női alak",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 58,
    title: "Mákvirág 2.",
    size: "8.8x7.0",
    externalSize: "11.2x9.2",
    price: 30000,
    category: "női alak",
    technique: "porcelán",
    description: "...",
    sold: false,
  },
  {
    id: 45,
    title: "Lovas kép 1.",
    size: "4.4x9.5",
    externalSize: "10.4x15.4",
    price: 30000,
    category: "állat",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  {
    id: 55,
    title: "Régi Magyarország",
    size: "9.3x13.9",
    externalSize: "12.9x16.9",
    price: 30000,
    category: "magyar történelem",
    technique: "üveg",
    description: "kész",
    sold: false,
  },
  {
    id: 41,
    title: "A nagy fa",
    size: "5.8x8.9",
    externalSize: "9.8x13.0",
    price: 30000,
    category: "természet",
    technique: "tűzzománc",
    description: "kész",
    sold: false,
  },
  // {
  //   id: 81,
  //   title: "Csónak",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "vászon",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 106,
  //   title: "Vadrózsa",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "virág",
  //   technique: "vászon",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 108,
  //   title: "Tájkép 1.",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "vászon",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 109,
  //   title: "Tájkép 2.",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "vászon",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 126,
  //   title: "Honfoglalás",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "magyar történelem",
  //   technique: "rajzlap",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 600,
  //   title: "Angyal",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "női alak",
  //   technique: "fa",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 601,
  //   title: "Szerelmes pár",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "szerelem",
  //   technique: "vászon",
  //   description: "...",
  //   sold: true,
  // },
  // {
  //   id: 602,
  //   title: "Két fa összefonódva",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "vászon",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 603,
  //   title: "Tulipánvirágok",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "virág",
  //   technique: "vászon",
  //   description: "...",
  //   sold: false,
  // },
  // {
  //   id: 114,
  //   title: "Élet fája",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "fa",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 115,
  //   title: "Szív mandala",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "mandala",
  //   technique: "fa",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 88,
  //   title: "Mandala 4",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "természet",
  //   technique: "fa",
  //   description: "kész",
  //   sold: false,
  // },
  // {
  //   id: 112,
  //   title: "Nap és Hold",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "vallási téma",
  //   technique: "vászon",
  //   description: "kész",
  //   sold: true,
  // },
  // {
  //   id: 113,
  //   title: "Jézus születése",
  //   size: "...",
  //   externalSize: "...",
  //   price: 30000,
  //   category: "vallási téma",
  //   technique: "vászon",
  //   description: "kész",
  //   sold: false,
  // },
];

// Normalizálás és duplikátumok eltávolítása
const uniqueGallery = {};
galleryData.forEach((item) => {
  if (!uniqueGallery[item.id]) {
    uniqueGallery[item.id] = item;
  }
});

const GALLERY = Object.values(uniqueGallery).sort((a, b) => b.id - a.id);

// Kiemelt képek - a kezdőoldalhoz (véletlenszerűen kiválasztott, de konzisztens)
const FEATURED_ITEMS = [7, 17, 62, 96, 107]
  .map((id) => GALLERY.find((item) => item.id === id))
  .filter(Boolean);

// Kategóriák
const CATEGORIES = ["tűzzománc", "porcelán", "fa", "vászon", "üveg", "rajzlap"];
